In [1]:
%matplotlib qt5
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import numpy as np
import h5py
import matplotlib.pyplot as plt
from pathlib import Path
import numpy.linalg as linalg

In [2]:
base_path = Path('/home/harsh/SpinorNagaraju/maps_1/stic/processed_inputs/')

In [3]:
inp_filename = 'alignedspectra_scan1_map01_Ca.fits_stic_profiles.nc'

In [4]:
f = h5py.File(base_path / inp_filename, 'r')

In [5]:
ind = np.where(f['profiles'][0, 0, 0, :, 0] != 0)[0]

In [6]:
data = f['profiles'][0, :, :, ind, :]

In [7]:
data.shape

(19, 60, 306, 4)

In [8]:
f.close()

In [9]:
in_data = data.reshape(19*60, 306, 4)

In [10]:
pca = PCA()

In [11]:
pca.fit(in_data[:, :, 0].copy())

PCA()

In [12]:
plt.plot(pca.explained_variance_ratio_)

In [24]:
tt = pca.fit_transform(in_data[:, :, 0].copy())

In [25]:
tt.shape

(1140, 306)

In [15]:
plt.plot(tt[0])

In [22]:
plt.plot(pca.components_[6])

In [37]:
kmeans = KMeans(tol=1e-6, n_clusters=30)

In [38]:
kmeans.fit(tt[:, 1:20])

KMeans(n_clusters=30, tol=1e-06)

In [39]:
kmeans.n_iter_

14

In [41]:
final_labels = kmeans.labels_.reshape(19, 60)

In [42]:
plt.imshow(final_labels, cmap='gray', origin='lower')

In [43]:
total_labels = final_labels.max() + 1

In [44]:
rps = np.zeros(
        (total_labels, ind.size, 4),
        dtype=np.float64
    )

In [45]:
for i in range(total_labels):
    a, b = np.where(final_labels == i)
    rps[i] = np.mean(data[a, b], axis=0)

In [46]:
final_labels[12, 40]

2

In [ ]:
plt.plot(data[12, 40, :, 0])

In [47]:
plt.plot(rps[2, :, 0])

In [48]:
a, b = np.where(final_labels == 2)

In [49]:
a, b

(array([ 7,  7,  9,  9,  9,  9, 10, 10, 10, 11, 11, 11, 12, 12, 12, 13, 13,
        14, 14, 15, 15, 16]),
 array([39, 40, 39, 40, 41, 42, 39, 40, 41, 39, 40, 41, 39, 40, 41, 37, 39,
        25, 37, 25, 36, 36]))

In [ ]:
f1 = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/chosen_out_30.h5', 'r')

In [ ]:
a1, b1 = np.where(f1['final_labels'][()] == 24)

In [ ]:
a1, b1

In [ ]:
mask = np.zeros_like(final_labels)

In [ ]:
mask[a, b] = 1

In [ ]:
plt.imshow(mask, cmap='gray', origin='lower')

In [50]:
final_labels[13, 27]

18

In [51]:
plt.plot(rps[18, :, 0])

In [52]:
a2, b2 = np.where(final_labels == 18)

In [53]:
a2, b2

(array([13, 13, 14, 14, 14, 15, 15, 15, 15]),
 array([26, 27, 26, 27, 28, 26, 27, 28, 29]))

In [ ]:
mask[a2, b2] = 1

In [ ]:
final_labels[5, 45]

In [ ]:
plt.plot(rps[20, :, 0])

In [ ]:
final_labels[12, 28]

In [ ]:
plt.plot(rps[4, :, 0])

In [ ]:
f1['final_labels'][12, 40]

In [ ]:
plt.plot(f1['rps'][12, :, 0])

In [ ]:
f1['final_labels'][()][a1, b1]

In [ ]:
final_labels[13, 26]

In [ ]:
plt.plot(rps[25, :, 0])

In [ ]:
a3, b3 = np.where(final_labels == 25)

In [ ]:
mask[a3, b3] = 1

In [ ]:
plt.imshow(mask, cmap='gray', origin='lower')

In [ ]:
plt.plot(data[10, 1, :, 0])

In [ ]:
final_labels[13, 29]

In [ ]:
plt.plot(rps[27, :, 0])

In [ ]:
a4, b4 = np.where(final_labels == 27)

In [ ]:
mask[a4, b4] = 1

In [ ]:
plt.imshow(mask, cmap='gray', origin='lower')

In [ ]:
a4, b4