In [144]:
%matplotlib qt5
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize

In [45]:
values = np.sin(np.deg2rad(2 * np.pi * np.arange(90000)) / 100) * 20

In [46]:
plt.plot(np.arange(90000) / 500, values)

In [49]:
s_values = np.sin(np.deg2rad(2 * np.pi * 500 * np.arange(90000))) * 5

In [50]:
plt.plot(s_values)

In [51]:
plt.plot(values + s_values)

In [55]:
total = values + s_values

In [186]:
kp = 0.5
ki = 0.01
kd = 0.5
ni=50
nd=5
new_values = list()
set_point = 0
prev_error = 0
prev_err_list = np.zeros(int(ni))
prev_derv_list = np.zeros(int(nd))
corr_err_list = list()
ii = 0
dd = 0
cilist = list()
cd_list = list()
for index, val in enumerate(total):
    if ii >= ni:
        ii = 0
    if dd >= nd:
        dd = 0
    err = set_point - val
    der_error = err - prev_error
    prev_err_list[ii] = err
    prev_derv_list[dd] = der_error
    cierror = np.sum(prev_err_list) / ni
    cderror = np.sum(prev_derv_list) / nd
    cilist.append(cierror)
    cd_list.append(cderror)
    corr_err = kp * err + ki * cierror + kd * cderror
    prev_error = err
    new_values.append(val + corr_err)

In [187]:
plt.plot(new_values)

In [183]:
np.std(new_values)

0.14286351550683776

In [169]:
def method_n(args):
    kp, ki, kd, ni, nd = args
    new_values = list()
    set_point = 0
    prev_error = 0
    prev_err_list = np.zeros(int(ni))
    prev_derv_list = np.zeros(int(nd))
    corr_err_list = list()
    ii = 0
    dd = 0
    cilist = list()
    cd_list = list()
    for index, val in enumerate(total):
        if ii >= ni:
            ii = 0
        if dd >= nd:
            dd = 0
        err = set_point - val
        der_error = err - prev_error
        prev_err_list[ii] = err
        prev_derv_list[dd] = der_error
        cierror = np.sum(prev_err_list) / ni
        cderror = np.sum(prev_derv_list) / nd
        cilist.append(cierror)
        cd_list.append(cderror)
        corr_err = kp * err + ki * cierror + kd * cderror
        prev_error = err
        new_values.append(val + corr_err)
    return np.std(new_values)
    

In [170]:
res = scipy.optimize.minimize(method_n, x0=(0.5, 0, 0.5, 50, 3), tol=1e-6)

In [171]:
res

  message: Desired error not necessarily achieved due to precision loss.
  success: False
   status: 2
      fun: 2.449918046467608e-06
        x: [ 9.998e-01  1.117e-02  1.360e-06  5.000e+01  3.173e+00]
      nit: 22
      jac: [-5.112e+00 -1.133e-01  1.409e+00  2.537e-05 -6.030e-07]
 hess_inv: [[ 2.793e-04 -1.401e-02 ...  9.589e-05  1.091e-06]
            [-1.401e-02  7.031e-01 ... -4.597e-03 -5.350e-05]
            ...
            [ 9.589e-05 -4.597e-03 ...  1.000e+00  1.473e-06]
            [ 1.091e-06 -5.350e-05 ...  1.473e-06  9.234e-01]]
     nfev: 612
     njev: 100