In [1]:
%matplotlib qt5
import h5py
import numpy as np
import matplotlib.pyplot as plt
import scipy.ndimage
from sklearn.decomposition import PCA

/home/harsh/CourseworkRepo/HMIAnalysis/env/lib/python3.7/site-packages/h5py/__init__.py:39: UserWarning: h5py is running against HDF5 1.12.2 when it was built against 1.12.1, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)


In [71]:
f = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/RPs_plots/rps_atmos_30_response.nc', 'r')
fo = h5py.File('aligned_Ca_Ha_stic_profiles.nc', 'r')

In [121]:
fa = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/fulldata_inversions/rps_atmos_30.nc', 'r')

In [72]:
ind = np.where(fo['profiles'][0, 0, 0, :, 0] != 0)[0]

In [73]:
ind.shape

(750,)

In [74]:
f['wav'][ind[0:306]]

array([8535.16582, 8535.19954, 8535.23326, 8535.26698, 8535.3007 ,
       8535.33442, 8535.36814, 8535.40186, 8535.43558, 8535.4693 ,
       8535.50302, 8535.53674, 8535.57046, 8535.60418, 8535.6379 ,
       8535.67162, 8535.70534, 8535.73906, 8535.77278, 8535.8065 ,
       8535.84022, 8535.87394, 8535.90766, 8535.94138, 8535.9751 ,
       8536.00882, 8536.04254, 8536.07626, 8536.10998, 8536.1437 ,
       8536.17742, 8536.21114, 8536.24486, 8536.27858, 8536.3123 ,
       8536.34602, 8536.37974, 8536.41346, 8536.44718, 8536.4809 ,
       8536.51462, 8536.54834, 8536.58206, 8536.61578, 8536.6495 ,
       8536.68322, 8536.71694, 8536.75066, 8536.78438, 8536.8181 ,
       8536.85182, 8536.88554, 8536.91926, 8536.95298, 8536.9867 ,
       8537.02042, 8537.05414, 8537.08786, 8537.18962, 8537.22334,
       8537.25706, 8537.29078, 8537.3245 , 8537.35822, 8537.39194,
       8537.42566, 8537.45938, 8537.4931 , 8537.52682, 8537.56054,
       8537.59426, 8537.62798, 8537.6617 , 8537.69542, 8537.72

In [3]:
ltau = np.array(
    [
        -8.        , -7.78133011, -7.77447987, -7.76711988, -7.76003981,
        -7.75249004, -7.74428988, -7.73559999, -7.72637987, -7.71590996,
        -7.7047801 , -7.69357014, -7.6876502 , -7.68174982, -7.67588997,
        -7.66997004, -7.66374016, -7.65712023, -7.64966011, -7.64093018,
        -7.63092995, -7.61920023, -7.60529995, -7.58876991, -7.56925011,
        -7.54674006, -7.52177   , -7.49316978, -7.45849991, -7.41659021,
        -7.36724997, -7.3108902 , -7.24834013, -7.18071985, -7.11129999,
        -7.04137993, -6.97006989, -6.89697981, -6.82298994, -6.74880981,
        -6.6747098 , -6.60046005, -6.52598   , -6.45187998, -6.37933016,
        -6.30926991, -6.24280977, -6.1792798 , -6.11685991, -6.05597019,
        -5.9974699 , -5.94147015, -5.88801003, -5.8468399 , -5.81285   ,
        -5.78013992, -5.74853992, -5.71774006, -5.68761015, -5.65824986,
        -5.62930012, -5.60065985, -5.57245016, -5.54456997, -5.51687002,
        -5.4893198 , -5.46182013, -5.43416977, -5.40622997, -5.3780098 ,
        -5.34959984, -5.32110977, -5.29247999, -5.26357985, -5.23412991,
        -5.20391989, -5.1728301 , -5.1407299 , -5.10780001, -5.07426023,
        -5.03998995, -5.00492001, -4.96953011, -4.9340601 , -4.89821005,
        -4.86195993, -4.82533979, -4.78824997, -4.75065994, -4.71243   ,
        -4.67438984, -4.63696003, -4.59945011, -4.56069994, -4.52212   ,
        -4.48434019, -4.44652987, -4.40795994, -4.36862993, -4.32842016,
        -4.28650999, -4.24205017, -4.19485998, -4.14490986, -4.09186983,
        -4.03446007, -3.97196007, -3.90451002, -3.83087993, -3.74959993,
        -3.66000009, -3.56112003, -3.45190001, -3.33172989, -3.20393991,
        -3.07448006, -2.94443989, -2.81389999, -2.68294001, -2.55164003,
        -2.4200201 , -2.28814006, -2.15604997, -2.02377009, -1.89135003,
        -1.75880003, -1.62612998, -1.49337006, -1.36126995, -1.23139   ,
        -1.10698998, -0.99208999, -0.884893  , -0.78278702, -0.68348801,
        -0.58499599, -0.48555899, -0.38308501, -0.27345601, -0.15217701,
        -0.0221309 ,  0.110786  ,  0.244405  ,  0.378378  ,  0.51182002,
        0.64473999,  0.777188  ,  0.90906298,  1.04043996,  1.17110002
    ]
)

In [76]:
f['derivatives'].shape

(1, 1, 30, 4, 150, 1236, 4)

In [119]:
plt.plot(f['wav'][ind[0:306]], f['profiles'][0, 0, 0, ind[0:306], 0])

In [118]:
plt.plot(f['wav'][ind[0:306]], f['profiles'][0, 0, 0, ind[0:306], 3] / f['profiles'][0, 0, 0, ind[0:306], 0])

In [124]:
X, Y = np.meshgrid(f['wav'][ind[0:306]], ltau)
plt.pcolormesh(X, Y, f['derivatives'][0, 0, 0, 3, :, ind[0:306], 3], cmap='gray', shading='nearest')

In [122]:
fp = h5py.File('pixel_indices_emission_total_6.h5', 'r')

In [125]:
plt.plot(ltau, fa['blong'][0, 0, 0])

In [14]:
fp.keys()

<KeysViewHDF5 ['pixel_indices']>

In [15]:
fp['pixel_indices'][()]

array([[12, 13, 14, 14, 15, 15],
       [28, 27, 26, 27, 26, 27],
       [24, 24, 24, 24, 24, 24]])

In [16]:
fp.close()

In [17]:
fp = h5py.File('pixel_indices_spot_total_107.h5', 'r')

In [21]:
np.unique(fp['pixel_indices'][2, :])

array([ 3,  9, 10, 13, 20, 21])

In [22]:
fp.close()

In [23]:
fp = h5py.File('pixel_indices_quiet_total_1027.h5', 'r')

In [28]:
x, y = fp['pixel_indices'][0:2]

In [25]:
fc = h5py.File('combined_output.nc', 'r')

In [26]:
fc.keys()

<KeysViewHDF5 ['blong', 'ltau500', 'nne', 'pgas', 'rho', 'temp', 'vlos', 'vturb', 'z']>

In [27]:
fc['temp'].shape

(1, 19, 60, 150)

In [29]:
x, y

(array([ 9,  9,  9, ..., 14, 14, 14]), array([57, 58, 59, ..., 49, 50, 51]))

In [30]:
fp.close()

In [31]:
fp = h5py.File('pixel_indices_emission_total_33.h5', 'r')

In [32]:
fp['pixel_indices'][2:]

array([[20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 24, 24, 24, 24, 24,
        24]])

In [33]:
fo = h5py.File('alignedspectra_scan1_map01_Ca.fits_stic_profiles.nc_emission_total_33.nc', 'r')

In [34]:
fo['profiles'].shape

(1, 1, 33, 1236, 4)

In [42]:
plt.plot(fo['wav'][ind[0:306]], scipy.ndimage.median_filter(fo['profiles'][0, 0, 12, ind[0:306], 3] / fo['profiles'][0, 0, 12, ind[0:306], 0], size=17))

In [54]:
fo.close()

In [126]:
fin = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/processed_inputs/alignedspectra_scan1_map01_Ca.fits_stic_profiles.nc', 'r')

In [128]:
fin['profiles'].shape

(1, 19, 60, 1236, 4)

In [149]:
stokes_v = fin['profiles'][0, 0, :, ind[0:306], 3]

In [150]:
stokes_v.shape

(60, 306)

In [151]:
plt.imshow(stokes_v, cmap='gray', origin='lower')

In [152]:
mu = np.mean(stokes_v, 0)

In [153]:
mu

array([ 4.26808742e-04,  2.98422474e-04,  1.80305699e-04,  2.10463821e-04,
        5.45665614e-06, -1.99085416e-05,  4.94770565e-05, -3.75236589e-04,
       -5.82270522e-04, -1.06452926e-05,  1.97691128e-04,  7.51080038e-05,
       -2.67244102e-04, -4.01926980e-04, -2.72757034e-04, -3.81879539e-04,
       -6.19270742e-04, -4.34529819e-04, -3.11574099e-04, -4.65527526e-04,
       -3.36605117e-04, -4.20825764e-04, -5.88580219e-04, -1.27075578e-03,
       -2.48335549e-03, -3.79541145e-03, -5.05636298e-03, -4.98523796e-03,
       -3.27156567e-03,  1.36942102e-04,  2.93376710e-03,  4.35442137e-03,
        4.03135270e-03,  3.16871507e-03,  2.06815308e-03,  1.23679329e-03,
        8.56534029e-04,  6.97170284e-04,  3.82526339e-04,  3.53396847e-04,
        4.15714444e-04,  1.66764481e-04,  1.43980309e-04,  4.52353293e-04,
        1.04195932e-04, -1.58498007e-04, -4.84558032e-05, -4.55545028e-05,
       -8.49467603e-05, -3.21484143e-04, -4.74829352e-04, -1.28052939e-04,
       -2.02208926e-04, -

In [289]:
pca = PCA(n_components=60)

In [290]:
nComps = 0
nCompe = 6
Xhat = np.dot(pca.fit_transform(stokes_v)[:,nComps:nCompe], pca.components_[nComps:nCompe,:])
Xhat += mu
plt.imshow(Xhat, cmap='gray', origin='lower')

In [291]:
features = range(pca.n_components_)
plt.bar(features, pca.explained_variance_ratio_, color='black')

<BarContainer object of 60 artists>

In [202]:
plt.plot(Xhat[30], label='corrected')
plt.plot(stokes_v[30], label='original')
plt.legend()

In [297]:
profiles = fin['profiles'][()]
for i in range(19):
    stokes_v = profiles[0, i, :, ind[0:306], 3]
    mu = np.mean(stokes_v, 0)
    pca = PCA(n_components=60)
    nComps = 0
    nCompe = 3
    Xhat = np.dot(pca.fit_transform(stokes_v)[:,nComps:nCompe], pca.components_[nComps:nCompe,:])
    Xhat += mu
    profiles[0, i, :, ind[0:306], 3] = Xhat

In [212]:
fin['wav'][1] - fin['wav'][0]

0.008432500000708387

In [310]:
plt.imshow(fin['profiles'][0, :, :, ind[0:306][0], 0], cmap='gray', origin='lower')

In [321]:
x=14
y=55

In [322]:
line1,  = plt.plot(fin['wav'][ind[0:306]], profiles[0, x, y, ind[0:306], 3] * 100/ profiles[0, x, y, ind[0:306], 0], label='corrected')
line2,  = plt.plot(fin['wav'][ind[0:306]], fin['profiles'][0, x, y, ind[0:306], 3] * 100/ fin['profiles'][0, x, y, ind[0:306], 0], label='original')
# plt.plot(fin['wav'][ind[0:306]], scipy.ndimage.gaussian_filter(fin['profiles'][0, x, y, ind[0:306], 3] / fin['profiles'][0, x, y, ind[0:306], 0], sigma=5/2.355, order=0), label='gaussian_filtered')
plt.gca().legend(handles=[line1, line2])
axs2 = plt.gca().twinx()
line3,  = axs2.plot(fin['wav'][ind[0:306]], fin['profiles'][0, x, y, ind[0:306], 0], label='profile', color='black')
axs2.legend(handles=[line3], loc=2)
# plt.legend()

In [260]:
fr = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/RPs_plots/new_inversions/rps_stic_profiles_x_30_y_1_cycle_1_t_0_vl_0_vt_0_blong_2_atmos_response.nc', 'r')

In [261]:
fr.keys()

<KeysViewHDF5 ['derivatives', 'ndep', 'profiles', 'stokes', 'time', 'vidx', 'vtype', 'wav', 'x', 'y']>

In [323]:
X, Y = np.meshgrid(fr['wav'][ind[0:306]], ltau)
plt.pcolormesh(X, Y, fr['derivatives'][0, 0, 0, 3, :, ind[0:306], 3], cmap='gray', shading='nearest')

In [312]:
fk = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/chosen_out_30.h5', 'r')

In [313]:
fk.keys()

<KeysViewHDF5 ['cluster_centers_', 'final_labels', 'inertia_', 'labels_', 'n_iter_', 'rps']>

In [314]:
mask = np.zeros_like(fk['final_labels'][()])

In [315]:
mask[np.where(fk['final_labels'][()] == 0)] = 1

In [316]:
plt.imshow(fin['profiles'][0, :, :, ind[0:306][0], 0], cmap='gray', origin='lower')
plt.contour(mask, levels=0)

/home/harsh/CourseworkRepo/HMIAnalysis/env/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: No contour levels were found within the data range.
  


In [318]:
np.where(fk['final_labels'][()] == 0)

(array([ 9,  9,  9, 10, 10, 10, 12, 12, 13, 13, 14, 14, 14, 14, 15, 15, 15,
        15, 15, 16, 16, 16, 16, 17, 17, 17, 17, 17, 18, 18]),
 array([57, 58, 59, 57, 58, 59, 56, 57, 55, 57, 55, 57, 58, 59, 55, 56, 57,
        58, 59, 56, 57, 58, 59, 55, 56, 57, 58, 59, 58, 59]))

In [324]:
fr2 = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/run_nagaraju/rps_stic_profiles_x_30_y_1_cycle_1_t_0_vl_0_vt_0_blong_2_atmos_intrep.nc', 'r+')

In [325]:
fr2.keys()

<KeysViewHDF5 ['azi', 'bhor', 'blong', 'cmass', 'ltau500', 'ndep', 'nne', 'pgas', 'rho', 'temp', 'time', 'vlos', 'vturb', 'x', 'y', 'z']>

In [326]:
blong = fr2['blong'][()]

In [327]:
blong.shape

(1, 1, 30, 150)

In [331]:
ltind = np.where((ltau<=-1.5) & (ltau>=-4))[0]

In [332]:
a, b = np.polyfit(ltau[ltind], blong[0, 0, 0, ltind], 1)

In [333]:
bln = a * ltau + b

In [334]:
plt.plot(ltau, bln)
plt.plot(ltau, blong[0, 0, 0])

In [335]:
for i in range(30):
    a, b = np.polyfit(ltau[ltind], blong[0, 0, i, ltind], 1)
    bln = a * ltau + b
    blong[0, 0, i] = bln

In [339]:
plt.plot(ltau, blong[0, 0, 29])

In [340]:
fr2

<HDF5 file "rps_stic_profiles_x_30_y_1_cycle_1_t_0_vl_0_vt_0_blong_2_atmos_intrep.nc" (mode r+)>

In [341]:
fr2['blong'][...] = blong

In [342]:
fr2.close()fr2 = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/run_nagaraju/rps_stic_profiles_x_30_y_1_cycle_1_t_0_vl_0_vt_0_blong_2_atmos_intrep_response.nc', 'r')

In [343]:
fr2 = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/run_nagaraju/rps_stic_profiles_x_30_y_1_cycle_1_t_0_vl_0_vt_0_blong_2_atmos_intrep_response.nc', 'r')

In [345]:
X, Y = np.meshgrid(fr2['wav'][ind[0:306]], ltau)
plt.pcolormesh(X, Y, fr2['derivatives'][0, 0, 0, 3, :, ind[0:306], 3], cmap='gray', shading='nearest')

In [346]:
fr3 = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/run_nagaraju/rps_stic_profiles_x_30_y_1_cycle_1_t_0_vl_0_vt_0_blong_2_atmos_intrep.nc', 'r')

In [349]:
plt.plot(ltau, fr3['vlos'][0, 0, 0]/1e5)

In [350]:
fr4 = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/run_nagaraju/rps_stic_profiles_x_30_y_1_cycle_1_t_0_vl_0_vt_0_blong_2_atmos_intrep_vlos_constant.nc', 'r+')

In [351]:
vlos = fr4['vlos'][()]

In [352]:
vlos.shape

(1, 1, 30, 150)

In [353]:
for i in range(30):
    vlos[0, 0, i] = np.mean(vlos[0, 0, i, ltind])

In [355]:
plt.plot(ltau, vlos[0, 0, 1]/1e5)

In [356]:
fr4['vlos'][...] = vlos

In [357]:
fr4.close()

In [358]:
fr4 = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/run_nagaraju/rps_stic_profiles_x_30_y_1_cycle_1_t_0_vl_0_vt_0_blong_2_atmos_intrep_vlos_constant_response.nc', 'r')

In [359]:
X, Y = np.meshgrid(fr4['wav'][ind[0:306]], ltau)
plt.pcolormesh(X, Y, fr4['derivatives'][0, 0, 0, 3, :, ind[0:306], 3], cmap='gray', shading='nearest')

In [360]:
fr4a = h5py.File('/home/harsh/SpinorNagaraju/maps_1/stic/run_nagaraju/rps_stic_profiles_x_30_y_1_cycle_1_t_0_vl_0_vt_0_blong_2_atmos_intrep_vlos_constant.nc', 'r')

In [362]:
plt.plot(ltau, fr4a['blong'][0, 0, 0])

In [31]:
f = h5py.File('/home/harsh/run_vishnu/Harsh_FALC_Atmosphere_response.nc', 'r')

In [15]:
wave = f['wav'][()] * 10

In [16]:
ind = np.where((wave >= 8530) & (wave <= 8550))[0]

In [17]:
ind.shape

(1404,)

In [18]:
f['derivatives'].shape

(1, 1, 12, 82, 1404, 4)

In [34]:
X, Y = np.meshgrid(f['wav'][ind] * 10, f['z'][0, 0, 0]/1e3)
plt.pcolormesh(X, Y, f['derivatives'][0, 0, 6, :, ind, 3], cmap='gray', shading='nearest')

In [13]:
np.arccos(1)

0.0

In [32]:
plt.plot(f['z'][0, 0, 0]/1e3, f['B_z'][0, 0, 0] * 1e4)