In [9]:
%matplotlib qt5
import h5py
import numpy as np
import matplotlib.pyplot as plt

In [24]:
f1 = h5py.File('combined_output_ha_profs_synth.nc', 'r')
f2 = h5py.File('aligned_Ca_Ha_stic_profiles.nc', 'r')

In [25]:
ind = np.where(f2['profiles'][0, 0, 0, 1236:, 0] != 0)[0]

In [26]:
ind+1236

array([1240, 1244, 1248, 1252, 1256, 1260, 1264, 1268, 1272, 1276, 1280,
       1284, 1288, 1292, 1296, 1300, 1304, 1308, 1312, 1316, 1320, 1324,
       1328, 1332, 1336, 1340, 1344, 1348, 1352, 1356, 1360, 1364, 1368,
       1372, 1376, 1380, 1384, 1388, 1392, 1396, 1400, 1404, 1408, 1412,
       1416, 1420, 1424, 1428, 1432, 1436, 1440, 1444, 1448, 1452, 1456,
       1460, 1464, 1468, 1472, 1476, 1480, 1484, 1488, 1492, 1496, 1500,
       1504, 1508, 1512, 1516, 1520, 1524, 1528, 1532, 1536, 1540, 1544,
       1548, 1552, 1556, 1560, 1564, 1568, 1572, 1576, 1580, 1584, 1588,
       1592, 1596, 1600, 1604, 1608, 1612, 1616, 1620, 1624, 1628, 1632,
       1636, 1640, 1644, 1648, 1652, 1656, 1660, 1664, 1668, 1672, 1676,
       1680, 1684, 1688, 1692, 1696, 1700, 1704, 1708, 1712, 1716, 1720,
       1724, 1728, 1732, 1736, 1740, 1744, 1748, 1752, 1756, 1760, 1764,
       1768, 1772, 1776, 1780, 1784, 1788, 1792, 1796, 1800, 1804, 1808,
       1812, 1816, 1820, 1824, 1828, 1832, 1836, 18

In [27]:
f2['profiles'].shape, f1['profiles'].shape

((1, 17, 60, 3016, 4), (1, 19, 60, 1780, 4))

In [28]:
f2['wav'][1236:], f1['wav'][()]

(array([6559.77655  , 6559.7821625, 6559.787775 , ..., 6569.7499625,
        6569.755575 , 6569.7611875]),
 array([6559.77655, 6559.78216, 6559.78777, ..., 6569.74552, 6569.75113,
        6569.75674]))

In [29]:
wave = 6562.8
wave_ind1 = np.argmin(np.abs(f1['wav'][()] - wave))
wave_ind2 = np.argmin(np.abs(f2['wav'][ind+1236] - wave))
fig, axs = plt.subplots(2, 1, figsize=(7, 5))
axs[0].imshow(f1['profiles'][0, 0:17, :, wave_ind1, 0], cmap='gray', origin='lower')
axs[1].imshow(f2['profiles'][0, 0:17, :, ind[wave_ind2] + 1236, 0], cmap='gray', origin='lower')

In [30]:
x=10
y=36
plt.plot(f1['wav'][()], f1['profiles'][0, x, y, :, 0], label='Synth')
plt.plot(f2['wav'][ind+1236], f2['profiles'][0, x, y, ind+1236, 0], label='obs')
plt.legend()

In [31]:
x=10
y=36
plt.plot(f1['wav'][()], f1['profiles'][0, x, y, :, 3] / f1['profiles'][0, x, y, :, 0], label='Synth')
plt.plot(f2['wav'][ind+1236], f2['profiles'][0, x, y, ind+1236, 3] / f2['profiles'][0, x, y, ind+1236, 0], label='obs')
plt.legend()